language: java
jdk:
- oraclejdk8
sudo: false

before_script: git clone -b travis `git config --get remote.origin.url` target/travis

script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy -P sonatype-oss-release -Dgpg.skip=true --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml'

after_success:
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:jacoco 

branches:
  only:
  - master

env:
  global:
  - secure: HqxtjbhRHcNxSpU3srVUcya+nULHrAj5eNLrUdH7pD6FRVI+HhARLgxEMdDxVlvQpvFBRuysjroXuny2iGPi/sgEk3pksdmXaI4iSK8xEGDjkJwdsgam7IzYjB+sPBSRilgdjUKshrHv7gQSR1xZJl5wnEYJbq/9Lf5TVuSVDE4=
  - secure: S+Oh909ZyNsEPG8jPzFIiPpwOfQLZPffoj018+HMl9kb5QxmzM0DCIBSY09sqWbmcD/Vl5EmuJpm5Qaq5rtO7LEPQ0VZavNhqTrjqLlqmwTWGyIJwvVde/LfSXMpAbzAE1Ockuc5ZtZpwwCMZFfzBOX29Vbb1LQWPU4FsO1718o=
